# -----------------------------------
# Conexión a PostgreSQL
# -----------------------------------
hibernate.connection.driver_class=org.postgresql.Driver
hibernate.connection.url=jdbc:postgresql://200.24.0.10:5432/depydb?reWriteBatchedInserts=true&stringtype=unspecified
hibernate.connection.username=postgres
hibernate.connection.password=$DoxaPostgres!

# -----------------------------------
# Pool de conexiones HikariCP
# -----------------------------------
hibernate.connection.provider_class=org.hibernate.hikaricp.internal.HikariCPConnectionProvider
hibernate.hikari.minimumIdle=5
hibernate.hikari.maximumPoolSize=20
hibernate.hikari.idleTimeout=300000
hibernate.hikari.maxLifetime=1800000
hibernate.hikari.poolName=depypoolHikari
hibernate.hikari.connectionTimeout=30000

# -----------------------------------
# Optimización de Hibernate para batch inserts/updates
# -----------------------------------
hibernate.jdbc.batch_size=50
hibernate.order_inserts=true
hibernate.order_updates=true
hibernate.jdbc.batch_versioned_data=true


# -----------------------------------
# Otros ajustes de rendimiento
# -----------------------------------
hibernate.format_sql=false
hibernate.use_sql_comments=false


